name: Build and Test AES

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential python3 python3-pip -y

    - name: Build C code
      run: make

    - name: Run Python tests
      run: |
        pip install pytest
        pytest test_aes.py
