name: AES SubBytes Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Python Tests
      run: |
        python -m unittest discover > result.log; tail -n 10 result.log

    - name: Install build-essential
      run: |
        sudo apt update
        sudo apt install -y build-essential
        sudo apt install -y libssl-dev

    - name: Compile C code
      run: |
        gcc main.c rijndael.c -o aes-encryption

    - name: Run C Tests
      run: |
        ./aes-encryption  > c_result.log; tail -n 10 c_result.log

    - name: Compare Results
      run: |
        python test_aes.py
